
import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";
import { getInitialLanguage } from "@/utils/languageDetection";

export type Language = "en" | "fr" | "ar" | "ha" | "ber";

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.about": "About",
    "nav.services": "Services",
    "nav.academy": "Academy",
    "nav.jobs": "Jobs",
    "nav.freelancers": "Freelancers",
    "nav.support": "Support",
    "nav.chat": "Chat",
    "nav.infrastructure": "Infrastructure",
    "nav.freeImeiCheck": "Free IMEI Check",
    "nav.more": "More",
    "nav.postJob": "Post Job",
    "nav.newsletter": "Newsletter",
    "nav.faq": "FAQ",
    "nav.rss": "RSS",
    "nav.privacyPolicy": "Privacy Policy",
    "nav.termsOfService": "Terms of Service",

    // Hero section
    "hero.headline": "Your Partner in Building, Repairing & Securing Digital Futures",
    "hero.subheadline": "Digital Solutions, Reimagined. Fix. Build. Secure. Empower.",
    "hero.description": "With over five years of dedicated experience in the IT industry, we provide comprehensive solutions spanning web development, cybersecurity, and advanced technical support. From custom Chrome extensions to IMEI services and BIOS repairs, we deliver excellence in every project.",
    "hero.cta1": "Explore Services",
    "hero.cta2": "Watch Demo",
    "hero.cta3": "Start Project",
    "hero.telegramNotice": "📢 Join our Telegram for instant tech news & updates!",
    "hero.stats.devicesRepaired": "Devices Repaired",
    "hero.stats.customerSatisfaction": "Customer Satisfaction",
    "hero.stats.yearsExperience": "Years Experience",
    "hero.stats.securityImprovement": "Security Improvement",

    // Services
    "services.ourServices": "Our Services",
    "services.ourServicesSubtitle": "Comprehensive digital solutions tailored to your needs",
    "services.allServices": "All Services",
    "services.development": "Development",
    "services.support": "Support",
    "services.security": "Security",
    "services.marketing": "Marketing",
    "services.getStartedToday": "Get Started Today",
    "services.pricing.from": "From",
    "services.pricing.perHour": "/hour",

    // Service categories
    "services.categories.webDevelopment": "Web Development",
    "services.categories.webDevelopmentDesc": "Custom websites and web applications built with modern technologies",
    "services.categories.itSupport": "IT Support",
    "services.categories.itSupportDesc": "Professional technical support and troubleshooting services",
    "services.categories.wordpress": "WordPress Development",
    "services.categories.wordpressDesc": "Custom WordPress themes, plugins, and website development",
    "services.categories.seo": "SEO Optimization",
    "services.categories.seoDesc": "Search engine optimization to improve your online visibility",
    "services.categories.systemSecurity": "System Security",
    "services.categories.systemSecurityDesc": "Comprehensive security audits and protection solutions",
    "services.categories.customTools": "Custom Tools",
    "services.categories.customToolsDesc": "Tailored software solutions and automation tools",

    // IMEI Checker
    "imei.title": "Free IMEI Checker",
    "imei.subtitle": "Check your device's IMEI information instantly and for free",
    "imei.description": "Instantly verify your device's IMEI information. Check if your phone is stolen, blocked, or has any issues before buying or selling.",
    "imei.enterImei": "Enter IMEI Number",
    "imei.placeholder": "e.g., 123456789012345",
    "imei.findImei": "Find your IMEI by dialing *#06# or checking Settings",
    "imei.checkImei": "Check IMEI",
    "imei.checking": "Checking...",
    "imei.reset": "Reset",
    "imei.error": "Error",
    "imei.errorEnterImei": "Please enter an IMEI number",
    "imei.errorInvalidImei": "IMEI should be exactly 15 digits",
    "imei.errorInvalidImeiDesc": "Invalid IMEI",
    "imei.results": "IMEI Check Results",
    "imei.whatIsImei": "What is IMEI?",
    "imei.imeiDescription": "IMEI (International Mobile Equipment Identity) is a unique 15-digit number that identifies your mobile device. It's useful for checking if a device is stolen, blocked, or has any issues before purchasing.",
    "imei.features.secure": "Secure & Private",
    "imei.features.secureDesc": "Your IMEI data is processed securely and not stored on our servers",
    "imei.features.instant": "Instant Results",
    "imei.features.instantDesc": "Get comprehensive IMEI information in seconds",
    "imei.features.free": "100% Free",
    "imei.features.freeDesc": "No registration required, completely free to use",

    // Service Request Form
    "form.requestService": "Request a Service",
    "form.yourName": "Your Name",
    "form.emailAddress": "Email Address",
    "form.phoneNumber": "Phone Number",
    "form.yourBudget": "Your Budget",
    "form.selectBudget": "Select a budget range",
    "form.lessThan300": "Less than $300",
    "form.budget300to500": "$300 - $500",
    "form.budget500to1000": "$500 - $1000",
    "form.budget1000to2000": "$1000 - $2000",
    "form.moreThan2000": "More than $2000",
    "form.contactForPricing": "Contact for pricing",
    "form.serviceInterested": "Service You're Interested In",
    "form.selectService": "Select a service",
    "form.webDevelopment": "Web Development",
    "form.itSupport": "IT Support",
    "form.wordpressDevelopment": "WordPress Development",
    "form.seoOptimization": "SEO Optimization",
    "form.systemSecurity": "System Security",
    "form.customToolsDevelopment": "Custom Tools Development",
    "form.imeiFrpRemote": "IMEI, FRP & Remote",
    "form.serverCardsGames": "Server, Cards & Games",
    "form.expertSupport": "Expert Support",
    "form.other": "Other (please specify in message)",
    "form.projectDetails": "Project Details",
    "form.projectDetailsPlaceholder": "Please describe your project or service needs in detail.",
    "form.submitRequest": "Submit Service Request",
    "form.submitting": "Submitting...",
    "form.submitted": "Service request submitted!",
    "form.submittedDesc": "Thanks for your interest. I'll get back to you within 24 hours.",
    "form.required": "*",

    // Jobs Page
    "jobs.title": "Find Your Next Job",
    "jobs.subtitle": "Discover opportunities in Tunisia's growing job market",
    "jobs.available": "Jobs Available",
    "jobs.filters": "Filters",
    "jobs.clear": "Clear",
    "jobs.searchJobs": "Search Jobs",
    "jobs.searchPlaceholder": "Job title, keywords...",
    "jobs.location": "Location",
    "jobs.locationPlaceholder": "City, region...",
    "jobs.category": "Category",
    "jobs.selectCategory": "Select category",
    "jobs.jobType": "Job Type",
    "jobs.selectJobType": "Select job type",
    "jobs.fullTime": "Full Time",
    "jobs.partTime": "Part Time",
    "jobs.contract": "Contract",
    "jobs.freelance": "Freelance",
    "jobs.salaryRange": "Salary Range (TND)",
    "jobs.urgencyLevel": "Urgency Level",
    "jobs.urgency.low": "Low",
    "jobs.urgency.medium": "Medium",
    "jobs.urgency.high": "High",
    "jobs.activeFilters": "Active Filters",
    "jobs.listView": "List View",
    "jobs.mapView": "Map View",
    "jobs.loading": "Loading jobs...",
    "jobs.noJobs": "No jobs found matching your criteria.",
    "jobs.error": "Error loading jobs. Please try again later.",

    // Common
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.success": "Success",
    "common.cancel": "Cancel",
    "common.save": "Save",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.confirm": "Confirm",
    "common.close": "Close",
    "common.search": "Search",
    "common.filter": "Filter",
    "common.sort": "Sort",
    "common.view": "View",
    "common.apply": "Apply",
    "common.reset": "Reset",
    "common.back": "Back",
    "common.next": "Next",
    "common.previous": "Previous",
    "common.submit": "Submit",
    "common.name": "Name",
    "common.email": "Email",
    "common.phone": "Phone",
    "common.message": "Message",
    "common.description": "Description",
    "common.title": "Title",
    "common.date": "Date",
    "common.time": "Time",
    "common.status": "Status",
    "common.action": "Action",
    "common.actions": "Actions"
  },

  fr: {
    // Navigation
    "nav.home": "Accueil",
    "nav.about": "À propos",
    "nav.services": "Services",
    "nav.academy": "Académie",
    "nav.jobs": "Emplois",
    "nav.freelancers": "Freelancers",
    "nav.support": "Support",
    "nav.chat": "Chat",
    "nav.infrastructure": "Infrastructure",
    "nav.freeImeiCheck": "Vérification IMEI Gratuite",
    "nav.more": "Plus",
    "nav.postJob": "Publier un Emploi",
    "nav.newsletter": "Newsletter",
    "nav.faq": "FAQ",
    "nav.rss": "RSS",
    "nav.privacyPolicy": "Politique de Confidentialité",
    "nav.termsOfService": "Conditions d'Utilisation",

    // Hero section
    "hero.headline": "Votre Partenaire pour Construire, Réparer et Sécuriser l'Avenir Numérique",
    "hero.subheadline": "Solutions Numériques, Réinventées. Réparer. Construire. Sécuriser. Autonomiser.",
    "hero.description": "Avec plus de cinq ans d'expérience dédiée dans l'industrie IT, nous fournissons des solutions complètes couvrant le développement web, la cybersécurité et le support technique avancé.",
    "hero.cta1": "Découvrir les Services",
    "hero.cta2": "Voir la Démo",
    "hero.cta3": "Démarrer un Projet",
    "hero.telegramNotice": "📢 Rejoignez notre Telegram pour les nouvelles tech instantanées!",
    "hero.stats.devicesRepaired": "Appareils Réparés",
    "hero.stats.customerSatisfaction": "Satisfaction Client",
    "hero.stats.yearsExperience": "Années d'Expérience",
    "hero.stats.securityImprovement": "Amélioration Sécurité",

    // Services
    "services.ourServices": "Nos Services",
    "services.ourServicesSubtitle": "Solutions numériques complètes adaptées à vos besoins",
    "services.allServices": "Tous les Services",
    "services.development": "Développement",
    "services.support": "Support",
    "services.security": "Sécurité",
    "services.marketing": "Marketing",
    "services.getStartedToday": "Commencer Aujourd'hui",
    "services.pricing.from": "À partir de",
    "services.pricing.perHour": "/heure",

    // Service categories
    "services.categories.webDevelopment": "Développement Web",
    "services.categories.webDevelopmentDesc": "Sites web et applications web personnalisés avec des technologies modernes",
    "services.categories.itSupport": "Support IT",
    "services.categories.itSupportDesc": "Support technique professionnel et services de dépannage",
    "services.categories.wordpress": "Développement WordPress",
    "services.categories.wordpressDesc": "Thèmes WordPress personnalisés, plugins et développement de sites web",
    "services.categories.seo": "Optimisation SEO",
    "services.categories.seoDesc": "Optimisation pour les moteurs de recherche pour améliorer votre visibilité en ligne",
    "services.categories.systemSecurity": "Sécurité Système",
    "services.categories.systemSecurityDesc": "Audits de sécurité complets et solutions de protection",
    "services.categories.customTools": "Outils Personnalisés",
    "services.categories.customToolsDesc": "Solutions logicielles sur mesure et outils d'automatisation",

    // IMEI Checker
    "imei.title": "Vérificateur IMEI Gratuit",
    "imei.subtitle": "Vérifiez les informations IMEI de votre appareil instantanément et gratuitement",
    "imei.description": "Vérifiez instantanément les informations IMEI de votre appareil. Vérifiez si votre téléphone est volé, bloqué ou a des problèmes avant d'acheter ou de vendre.",
    "imei.enterImei": "Entrez le Numéro IMEI",
    "imei.placeholder": "ex. 123456789012345",
    "imei.findImei": "Trouvez votre IMEI en composant *#06# ou en vérifiant les Paramètres",
    "imei.checkImei": "Vérifier IMEI",
    "imei.checking": "Vérification...",
    "imei.reset": "Réinitialiser",
    "imei.error": "Erreur",
    "imei.errorEnterImei": "Veuillez entrer un numéro IMEI",
    "imei.errorInvalidImei": "L'IMEI doit être exactement de 15 chiffres",
    "imei.errorInvalidImeiDesc": "IMEI invalide",
    "imei.results": "Résultats de Vérification IMEI",
    "imei.whatIsImei": "Qu'est-ce que l'IMEI?",
    "imei.imeiDescription": "IMEI (International Mobile Equipment Identity) est un numéro unique de 15 chiffres qui identifie votre appareil mobile. Il est utile pour vérifier si un appareil est volé, bloqué ou a des problèmes avant l'achat.",
    "imei.features.secure": "Sécurisé et Privé",
    "imei.features.secureDesc": "Vos données IMEI sont traitées de manière sécurisée et ne sont pas stockées sur nos serveurs",
    "imei.features.instant": "Résultats Instantanés",
    "imei.features.instantDesc": "Obtenez des informations IMEI complètes en quelques secondes",
    "imei.features.free": "100% Gratuit",
    "imei.features.freeDesc": "Aucune inscription requise, complètement gratuit à utiliser",

    // Service Request Form
    "form.requestService": "Demander un Service",
    "form.yourName": "Votre Nom",
    "form.emailAddress": "Adresse Email",
    "form.phoneNumber": "Numéro de Téléphone",
    "form.yourBudget": "Votre Budget",
    "form.selectBudget": "Sélectionnez une fourchette de budget",
    "form.lessThan300": "Moins de 300€",
    "form.budget300to500": "300€ - 500€",
    "form.budget500to1000": "500€ - 1000€",
    "form.budget1000to2000": "1000€ - 2000€",
    "form.moreThan2000": "Plus de 2000€",
    "form.contactForPricing": "Contactez pour le prix",
    "form.serviceInterested": "Service qui vous intéresse",
    "form.selectService": "Sélectionnez un service",
    "form.webDevelopment": "Développement Web",
    "form.itSupport": "Support IT",
    "form.wordpressDevelopment": "Développement WordPress",
    "form.seoOptimization": "Optimisation SEO",
    "form.systemSecurity": "Sécurité Système",
    "form.customToolsDevelopment": "Développement d'Outils Personnalisés",
    "form.imeiFrpRemote": "IMEI, FRP et Remote",
    "form.serverCardsGames": "Serveur, Cartes et Jeux",
    "form.expertSupport": "Support Expert",
    "form.other": "Autre (veuillez préciser dans le message)",
    "form.projectDetails": "Détails du Projet",
    "form.projectDetailsPlaceholder": "Veuillez décrire votre projet ou vos besoins de service en détail.",
    "form.submitRequest": "Soumettre la Demande de Service",
    "form.submitting": "Soumission...",
    "form.submitted": "Demande de service soumise!",
    "form.submittedDesc": "Merci pour votre intérêt. Je vous répondrai dans les 24 heures.",
    "form.required": "*",

    // Jobs Page
    "jobs.title": "Trouvez Votre Prochain Emploi",
    "jobs.subtitle": "Découvrez les opportunités dans le marché du travail croissant de la Tunisie",
    "jobs.available": "Emplois Disponibles",
    "jobs.filters": "Filtres",
    "jobs.clear": "Effacer",
    "jobs.searchJobs": "Rechercher des Emplois",
    "jobs.searchPlaceholder": "Titre du poste, mots-clés...",
    "jobs.location": "Lieu",
    "jobs.locationPlaceholder": "Ville, région...",
    "jobs.category": "Catégorie",
    "jobs.selectCategory": "Sélectionner une catégorie",
    "jobs.jobType": "Type d'Emploi",
    "jobs.selectJobType": "Sélectionner un type d'emploi",
    "jobs.fullTime": "Temps Plein",
    "jobs.partTime": "Temps Partiel",
    "jobs.contract": "Contrat",
    "jobs.freelance": "Freelance",
    "jobs.salaryRange": "Fourchette de Salaire (TND)",
    "jobs.urgencyLevel": "Niveau d'Urgence",
    "jobs.urgency.low": "Faible",
    "jobs.urgency.medium": "Moyen",
    "jobs.urgency.high": "Élevé",
    "jobs.activeFilters": "Filtres Actifs",
    "jobs.listView": "Vue Liste",
    "jobs.mapView": "Vue Carte",
    "jobs.loading": "Chargement des emplois...",
    "jobs.noJobs": "Aucun emploi trouvé correspondant à vos critères.",
    "jobs.error": "Erreur lors du chargement des emplois. Veuillez réessayer plus tard.",

    // Common
    "common.loading": "Chargement...",
    "common.error": "Erreur",
    "common.success": "Succès",
    "common.cancel": "Annuler",
    "common.save": "Sauvegarder",
    "common.edit": "Modifier",
    "common.delete": "Supprimer",
    "common.confirm": "Confirmer",
    "common.close": "Fermer",
    "common.search": "Rechercher",
    "common.filter": "Filtrer",
    "common.sort": "Trier",
    "common.view": "Voir",
    "common.apply": "Appliquer",
    "common.reset": "Réinitialiser",
    "common.back": "Retour",
    "common.next": "Suivant",
    "common.previous": "Précédent",
    "common.submit": "Soumettre",
    "common.name": "Nom",
    "common.email": "Email",
    "common.phone": "Téléphone",
    "common.message": "Message",
    "common.description": "Description",
    "common.title": "Titre",
    "common.date": "Date",
    "common.time": "Heure",
    "common.status": "Statut",
    "common.action": "Action",
    "common.actions": "Actions"
  },

  ar: {
    // Navigation
    "nav.home": "الرئيسية",
    "nav.about": "حول",
    "nav.services": "الخدمات",
    "nav.academy": "الأكاديمية",
    "nav.jobs": "الوظائف",
    "nav.freelancers": "المستقلون",
    "nav.support": "الدعم",
    "nav.chat": "الدردشة",
    "nav.infrastructure": "البنية التحتية",
    "nav.freeImeiCheck": "فحص IMEI مجاني",
    "nav.more": "المزيد",
    "nav.postJob": "نشر وظيفة",
    "nav.newsletter": "النشرة الإخبارية",
    "nav.faq": "الأسئلة الشائعة",
    "nav.rss": "RSS",
    "nav.privacyPolicy": "سياسة الخصوصية",
    "nav.termsOfService": "شروط الخدمة",

    // Hero section
    "hero.headline": "شريكك في بناء وإصلاح وتأمين المستقبل الرقمي",
    "hero.subheadline": "حلول رقمية مبتكرة. إصلاح. بناء. حماية. تمكين.",
    "hero.description": "مع أكثر من خمس سنوات من الخبرة المتخصصة في صناعة تقنية المعلومات، نقدم حلولاً شاملة تشمل تطوير الويب والأمن السيبراني والدعم التقني المتقدم.",
    "hero.cta1": "استكشف الخدمات",
    "hero.cta2": "شاهد العرض",
    "hero.cta3": "ابدأ مشروع",
    "hero.telegramNotice": "📢 انضم إلى تلغرام للأخبار التقنية الفورية!",
    "hero.stats.devicesRepaired": "جهاز تم إصلاحه",
    "hero.stats.customerSatisfaction": "رضا العملاء",
    "hero.stats.yearsExperience": "سنوات خبرة",
    "hero.stats.securityImprovement": "تحسين الأمان",

    // Services
    "services.ourServices": "خدماتنا",
    "services.ourServicesSubtitle": "حلول رقمية شاملة مصممة خصيصاً لاحتياجاتك",
    "services.allServices": "جميع الخدمات",
    "services.development": "التطوير",
    "services.support": "الدعم",
    "services.security": "الأمان",
    "services.marketing": "التسويق",
    "services.getStartedToday": "ابدأ اليوم",
    "services.pricing.from": "من",
    "services.pricing.perHour": "/ساعة",

    // Service categories
    "services.categories.webDevelopment": "تطوير الويب",
    "services.categories.webDevelopmentDesc": "مواقع ويب وتطبيقات ويب مخصصة مبنية بتقنيات حديثة",
    "services.categories.itSupport": "دعم تقني",
    "services.categories.itSupportDesc": "دعم تقني محترف وخدمات استكشاف الأخطاء وإصلاحها",
    "services.categories.wordpress": "تطوير ووردبريس",
    "services.categories.wordpressDesc": "قوالب ووردبريس مخصصة والإضافات وتطوير المواقع",
    "services.categories.seo": "تحسين محركات البحث",
    "services.categories.seoDesc": "تحسين محركات البحث لتحسين ظهورك على الإنترنت",
    "services.categories.systemSecurity": "أمان الأنظمة",
    "services.categories.systemSecurityDesc": "تدقيق أمني شامل وحلول الحماية",
    "services.categories.customTools": "أدوات مخصصة",
    "services.categories.customToolsDesc": "حلول برمجية مخصصة وأدوات أتمتة",

    // IMEI Checker
    "imei.title": "فاحص IMEI مجاني",
    "imei.subtitle": "تحقق من معلومات IMEI لجهازك فوراً ومجاناً",
    "imei.description": "تحقق فوراً من معلومات IMEI لجهازك. تحقق مما إذا كان هاتفك مسروق أو محظور أو به مشاكل قبل الشراء أو البيع.",
    "imei.enterImei": "أدخل رقم IMEI",
    "imei.placeholder": "مثال: 123456789012345",
    "imei.findImei": "اعثر على IMEI الخاص بك بطلب *#06# أو فحص الإعدادات",
    "imei.checkImei": "فحص IMEI",
    "imei.checking": "جارٍ الفحص...",
    "imei.reset": "إعادة تعيين",
    "imei.error": "خطأ",
    "imei.errorEnterImei": "يرجى إدخال رقم IMEI",
    "imei.errorInvalidImei": "يجب أن يكون IMEI بالضبط 15 رقماً",
    "imei.errorInvalidImeiDesc": "IMEI غير صحيح",
    "imei.results": "نتائج فحص IMEI",
    "imei.whatIsImei": "ما هو IMEI؟",
    "imei.imeiDescription": "IMEI (الهوية الدولية لمعدات الهاتف المحمول) هو رقم فريد مكون من 15 رقماً يحدد جهازك المحمول. إنه مفيد للتحقق مما إذا كان الجهاز مسروقاً أو محظوراً أو به مشاكل قبل الشراء.",
    "imei.features.secure": "آمن وخاص",
    "imei.features.secureDesc": "يتم معالجة بيانات IMEI الخاصة بك بشكل آمن ولا يتم تخزينها على خوادمنا",
    "imei.features.instant": "نتائج فورية",
    "imei.features.instantDesc": "احصل على معلومات IMEI شاملة في ثوان",
    "imei.features.free": "100% مجاني",
    "imei.features.freeDesc": "لا يتطلب تسجيل، مجاني تماماً للاستخدام",

    // Service Request Form
    "form.requestService": "طلب خدمة",
    "form.yourName": "اسمك",
    "form.emailAddress": "عنوان البريد الإلكتروني",
    "form.phoneNumber": "رقم الهاتف",
    "form.yourBudget": "ميزانيتك",
    "form.selectBudget": "اختر نطاق الميزانية",
    "form.lessThan300": "أقل من 300 دولار",
    "form.budget300to500": "300 - 500 دولار",
    "form.budget500to1000": "500 - 1000 دولار",
    "form.budget1000to2000": "1000 - 2000 دولار",
    "form.moreThan2000": "أكثر من 2000 دولار",
    "form.contactForPricing": "اتصل للحصول على السعر",
    "form.serviceInterested": "الخدمة التي تهتم بها",
    "form.selectService": "اختر خدمة",
    "form.webDevelopment": "تطوير الويب",
    "form.itSupport": "دعم تقني",
    "form.wordpressDevelopment": "تطوير ووردبريس",
    "form.seoOptimization": "تحسين محركات البحث",
    "form.systemSecurity": "أمان الأنظمة",
    "form.customToolsDevelopment": "تطوير أدوات مخصصة",
    "form.imeiFrpRemote": "IMEI، FRP والتحكم عن بُعد",
    "form.serverCardsGames": "الخادم والبطاقات والألعاب",
    "form.expertSupport": "دعم خبير",
    "form.other": "أخرى (يرجى التوضيح في الرسالة)",
    "form.projectDetails": "تفاصيل المشروع",
    "form.projectDetailsPlaceholder": "يرجى وصف مشروعك أو احتياجات الخدمة بالتفصيل.",
    "form.submitRequest": "إرسال طلب الخدمة",
    "form.submitting": "جارٍ الإرسال...",
    "form.submitted": "تم إرسال طلب الخدمة!",
    "form.submittedDesc": "شكراً لاهتمامك. سأرد عليك خلال 24 ساعة.",
    "form.required": "*",

    // Jobs Page
    "jobs.title": "اعثر على وظيفتك التالية",
    "jobs.subtitle": "اكتشف الفرص في سوق العمل المتنامي في تونس",
    "jobs.available": "الوظائف المتاحة",
    "jobs.filters": "المرشحات",
    "jobs.clear": "مسح",
    "jobs.searchJobs": "البحث عن وظائف",
    "jobs.searchPlaceholder": "عنوان الوظيفة، كلمات مفتاحية...",
    "jobs.location": "الموقع",
    "jobs.locationPlaceholder": "المدينة، المنطقة...",
    "jobs.category": "الفئة",
    "jobs.selectCategory": "اختر فئة",
    "jobs.jobType": "نوع الوظيفة",
    "jobs.selectJobType": "اختر نوع الوظيفة",
    "jobs.fullTime": "دوام كامل",
    "jobs.partTime": "دوام جزئي",
    "jobs.contract": "عقد",
    "jobs.freelance": "عمل حر",
    "jobs.salaryRange": "نطاق الراتب (دينار تونسي)",
    "jobs.urgencyLevel": "مستوى الإلحاح",
    "jobs.urgency.low": "منخفض",
    "jobs.urgency.medium": "متوسط",
    "jobs.urgency.high": "عالي",
    "jobs.activeFilters": "المرشحات النشطة",
    "jobs.listView": "عرض القائمة",
    "jobs.mapView": "عرض الخريطة",
    "jobs.loading": "جارٍ تحميل الوظائف...",
    "jobs.noJobs": "لم يتم العثور على وظائف تطابق معاييرك.",
    "jobs.error": "خطأ في تحميل الوظائف. يرجى المحاولة مرة أخرى لاحقاً.",

    // Common
    "common.loading": "جارٍ التحميل...",
    "common.error": "خطأ",
    "common.success": "نجح",
    "common.cancel": "إلغاء",
    "common.save": "حفظ",
    "common.edit": "تعديل",
    "common.delete": "حذف",
    "common.confirm": "تأكيد",
    "common.close": "إغلاق",
    "common.search": "بحث",
    "common.filter": "مرشح",
    "common.sort": "ترتيب",
    "common.view": "عرض",
    "common.apply": "تطبيق",
    "common.reset": "إعادة تعيين",
    "common.back": "رجوع",
    "common.next": "التالي",
    "common.previous": "السابق",
    "common.submit": "إرسال",
    "common.name": "الاسم",
    "common.email": "البريد الإلكتروني",
    "common.phone": "الهاتف",
    "common.message": "الرسالة",
    "common.description": "الوصف",
    "common.title": "العنوان",
    "common.date": "التاريخ",
    "common.time": "الوقت",
    "common.status": "الحالة",
    "common.action": "الإجراء",
    "common.actions": "الإجراءات"
  },

  ha: {
    // Navigation
    "nav.home": "Gida",
    "nav.about": "Game da mu",
    "nav.services": "Ayyuka",
    "nav.academy": "Makaranta",
    "nav.jobs": "Ayyukan yi",
    "nav.freelancers": "Masu aikin kansu",
    "nav.support": "Tallafi",
    "nav.chat": "Hira",
    "nav.infrastructure": "Kayan aiki",
    "nav.freeImeiCheck": "Binciken IMEI kyauta",
    "nav.more": "Ƙari",
    "nav.postJob": "Buga aiki",
    "nav.newsletter": "Wasiƙar labarai",
    "nav.faq": "Tambayoyin da ake yawan yi",
    "nav.rss": "RSS",
    "nav.privacyPolicy": "Manufar sirri",
    "nav.termsOfService": "Sharuɗɗan sabis",

    // Hero section
    "hero.headline": "Abokin aikinku wajen ginawa, gyarawa da kare makomar dijital",
    "hero.subheadline": "Hanyoyin dijital, An sake ƙirƙira. Gyarawa. Gina. Kare. Ƙarfafawa.",
    "hero.description": "Tare da sama da shekaru biyar na ƙwarewar keɓantacce a cikin masana'antar IT, muna ba da cikakkun mafita da suka ƙunshi haɓaka gidajen yanar gizo, tsaro na yanar gizo, da tallafin fasaha na ci gaba.",
    "hero.cta1": "Binciko Ayyuka",
    "hero.cta2": "Kalli Demo",
    "hero.cta3": "Fara Aikin",
    "hero.telegramNotice": "📢 Shiga Telegram ɗinmu don samun labaran fasaha nan take!",
    "hero.stats.devicesRepaired": "Na'urori da aka gyara",
    "hero.stats.customerSatisfaction": "Gamsuwar abokan ciniki",
    "hero.stats.yearsExperience": "Shekarun ƙwarewa",
    "hero.stats.securityImprovement": "Haɓaka tsaro",

    // Services
    "services.ourServices": "Ayyukanmu",
    "services.ourServicesSubtitle": "Cikakkun hanyoyin dijital da aka keɓance don bukatunku",
    "services.allServices": "Duk Ayyuka",
    "services.development": "Haɓakawa",
    "services.support": "Tallafi",
    "services.security": "Tsaro",
    "services.marketing": "Tallan",
    "services.getStartedToday": "Fara yau",
    "services.pricing.from": "Daga",
    "services.pricing.perHour": "/awa",

    // Service categories
    "services.categories.webDevelopment": "Haɓaka gidajen yanar gizo",
    "services.categories.webDevelopmentDesc": "Gidajen yanar gizo da aikace-aikacen yanar gizo na musamman da aka gina da fasahar zamani",
    "services.categories.itSupport": "Tallafin IT",
    "services.categories.itSupportDesc": "Tallafin fasaha na ƙwarewa da ayyukan warware matsaloli",
    "services.categories.wordpress": "Haɓaka WordPress",
    "services.categories.wordpressDesc": "Jigogin WordPress na musamman, plugins da haɓaka gidajen yanar gizo",
    "services.categories.seo": "Inganta SEO",
    "services.categories.seoDesc": "Inganta injin binciken don inganta bayyanarku a yanar gizo",
    "services.categories.systemSecurity": "Tsaron tsarin",
    "services.categories.systemSecurityDesc": "Cikakkun binciken tsaro da hanyoyin kariya",
    "services.categories.customTools": "Kayan aiki na musamman",
    "services.categories.customToolsDesc": "Hanyoyin software na musamman da kayan aikin automation",

    // IMEI Checker
    "imei.title": "Mai binciken IMEI kyauta",
    "imei.subtitle": "Binciko bayanan IMEI na na'urarku nan take kuma kyauta",
    "imei.description": "Binciko nan take bayanan IMEI na na'urarku. Binciko ko wayarku an sace ta, an toshe ta ko tana da matsaloli kafin siyarwa ko sayarwa.",
    "imei.enterImei": "Shigar da lambar IMEI",
    "imei.placeholder": "misali: 123456789012345",
    "imei.findImei": "Nemo IMEI ɗinku ta hanyar buga *#06# ko binciko Saituna",
    "imei.checkImei": "Binciko IMEI",
    "imei.checking": "Ana bincike...",
    "imei.reset": "Sake saiti",
    "imei.error": "Kuskure",
    "imei.errorEnterImei": "Da fatan za a shigar da lambar IMEI",
    "imei.errorInvalidImei": "IMEI ya kamata ya zama lambobi 15 daidai",
    "imei.errorInvalidImeiDesc": "IMEI mara inganci",
    "imei.results": "Sakamakon binciken IMEI",
    "imei.whatIsImei": "Menene IMEI?",
    "imei.imeiDescription": "IMEI (International Mobile Equipment Identity) lambar ce ta musamman mai lambobi 15 da ke gane na'urar wayar hannu. Yana da amfani don binciko ko na'urar an sace ta, an toshe ta ko tana da matsaloli kafin siyarwa.",
    "imei.features.secure": "Amintacce da sirri",
    "imei.features.secureDesc": "Ana sarrafa bayanan IMEI ɗinku cikin aminci kuma ba a adana su a sabar mu ba",
    "imei.features.instant": "Sakamako nan take",
    "imei.features.instantDesc": "Samun cikakkun bayanan IMEI a cikin dakika",
    "imei.features.free": "100% kyauta",
    "imei.features.freeDesc": "Ba a buƙatar rajista, kyauta gaba ɗaya don amfani",

    // Service Request Form
    "form.requestService": "Neman sabis",
    "form.yourName": "Sunanku",
    "form.emailAddress": "Adireshin imel",
    "form.phoneNumber": "Lambar waya",
    "form.yourBudget": "Kasafin kuɗinku",
    "form.selectBudget": "Zaɓi kewayon kasafin kuɗi",
    "form.lessThan300": "Ƙasa da $300",
    "form.budget300to500": "$300 - $500",
    "form.budget500to1000": "$500 - $1000",
    "form.budget1000to2000": "$1000 - $2000",
    "form.moreThan2000": "Sama da $2000",
    "form.contactForPricing": "Tuntuɓe don farashin",
    "form.serviceInterested": "Sabis da kuke sha'awar",
    "form.selectService": "Zaɓi sabis",
    "form.webDevelopment": "Haɓaka gidajen yanar gizo",
    "form.itSupport": "Tallafin IT",
    "form.wordpressDevelopment": "Haɓaka WordPress",
    "form.seoOptimization": "Inganta SEO",
    "form.systemSecurity": "Tsaron tsarin",
    "form.customToolsDevelopment": "Haɓaka kayan aiki na musamman",
    "form.imeiFrpRemote": "IMEI, FRP da Nesa",
    "form.serverCardsGames": "Sabar, Katuna da Wasanni",
    "form.expertSupport": "Tallafin gwani",
    "form.other": "Wani (da fatan za a bayyana a cikin saƙo)",
    "form.projectDetails": "Cikakkun bayanan aikin",
    "form.projectDetailsPlaceholder": "Da fatan za a bayyana aikinku ko bukatun sabis dalla-dalla.",
    "form.submitRequest": "Tura buƙatar sabis",
    "form.submitting": "Ana turawa...",
    "form.submitted": "An tura buƙatar sabis!",
    "form.submittedDesc": "Na gode da sha'awarku. Zan amsa muku cikin sa'o'i 24.",
    "form.required": "*",

    // Jobs Page
    "jobs.title": "Nemo aikinku na gaba",
    "jobs.subtitle": "Gano damar a cikin kasuwar aiki mai haɓaka ta Tunisia",
    "jobs.available": "Ayyukan da ake da su",
    "jobs.filters": "Tacewa",
    "jobs.clear": "Share",
    "jobs.searchJobs": "Neman ayyuka",
    "jobs.searchPlaceholder": "Taken aiki, kalmomin maɓalli...",
    "jobs.location": "Wurin",
    "jobs.locationPlaceholder": "Birni, yanki...",
    "jobs.category": "Nau'i",
    "jobs.selectCategory": "Zaɓi nau'i",
    "jobs.jobType": "Nau'in aiki",
    "jobs.selectJobType": "Zaɓi nau'in aiki",
    "jobs.fullTime": "Cikakken lokaci",
    "jobs.partTime": "Wani lokaci",
    "jobs.contract": "Kwangila",
    "jobs.freelance": "Aikin 'yanci",
    "jobs.salaryRange": "Kewayon albashi (TND)",
    "jobs.urgencyLevel": "Matakin gaggawa",
    "jobs.urgency.low": "Ƙanana",
    "jobs.urgency.medium": "Matsakaici",
    "jobs.urgency.high": "Babba",
    "jobs.activeFilters": "Tacewa masu aiki",
    "jobs.listView": "Kallon jeri",
    "jobs.mapView": "Kallon taswira",
    "jobs.loading": "Ana loda ayyuka...",
    "jobs.noJobs": "Ba a sami ayyukan da suka dace da ka'idodinku ba.",
    "jobs.error": "Kuskure wajen loda ayyuka. Da fatan za a sake gwadawa daga baya.",

    // Common
    "common.loading": "Ana lodawa...",
    "common.error": "Kuskure",
    "common.success": "Nasara",
    "common.cancel": "Soke",
    "common.save": "Ajiye",
    "common.edit": "Gyara",
    "common.delete": "Share",
    "common.confirm": "Tabbatar",
    "common.close": "Rufe",
    "common.search": "Bincike",
    "common.filter": "Tace",
    "common.sort": "Jera",
    "common.view": "Kallo",
    "common.apply": "Yi amfani",
    "common.reset": "Sake saiti",
    "common.back": "Komawa",
    "common.next": "Na gaba",
    "common.previous": "Na baya",
    "common.submit": "Tura",
    "common.name": "Suna",
    "common.email": "Imel",
    "common.phone": "Waya",
    "common.message": "Saƙo",
    "common.description": "Bayanin",
    "common.title": "Taken",
    "common.date": "Kwanan wata",
    "common.time": "Lokaci",
    "common.status": "Matsayi",
    "common.action": "Aiki",
    "common.actions": "Ayyuka"
  },

  ber: {
    // Navigation
    "nav.home": "Axxam",
    "nav.about": "Ɣef-nneɣ",
    "nav.services": "Imeẓla",
    "nav.academy": "Aɣerbaz",
    "nav.jobs": "Ixeddamen",
    "nav.freelancers": "Imahilayen ilelliyen",
    "nav.support": "Allal",
    "nav.chat": "Ameslay",
    "nav.infrastructure": "Talast n uzadur",
    "nav.freeImeiCheck": "Asenqed n IMEI baṭel",
    "nav.more": "Ugar",
    "nav.postJob": "Aru axeddim",
    "nav.newsletter": "Tabratt n telɣut",
    "nav.faq": "Isteqsiyen igettusuqqlen",
    "nav.rss": "RSS",
    "nav.privacyPolicy": "Tasertit n tbaḍnit",
    "nav.termsOfService": "Tiwtilin n umeẓlu",

    // Hero section
    "hero.headline": "Amendid-inek deg ubani, aseggem d uctaεa n zik d imal",
    "hero.subheadline": "Tifrat n umaḍal n usuddem, ttusniɣent. Seggem. Bnu. Ḥrez. Sεu tazmert.",
    "hero.description": "S wugar n semmus iseggasen n tirmit tusligt deg umasal n tetiknulujiyin n telɣut, d-nettmuddu tifrat tiččurin yellan deg usnefli n usawen web, amman n usuddem, d tallalt tatiknikt taneggidt.",
    "hero.cta1": "Issin imeẓla",
    "hero.cta2": "Ẓer beṭṭu",
    "hero.cta3": "Bdu asenfar",
    "hero.telegramNotice": "📢 Ddu-d ɣer Telegram-nneɣ i telɣut tatiknikt deg wakud!",
    "hero.stats.devicesRepaired": "Ibenkan yettuseggmen",
    "hero.stats.customerSatisfaction": "Aḍfar n imsaɣen",
    "hero.stats.yearsExperience": "Iseggasen n tirmit",
    "hero.stats.securityImprovement": "Asnerni n tɣellist",

    // Services
    "services.ourServices": "Imeẓla-nneɣ",
    "services.ourServicesSubtitle": "Tifrat tiččurin n umaḍal usuddem i yettusmenyifen i wayen tesriḍ",
    "services.allServices": "Akk imeẓla",
    "services.development": "Asnefli",
    "services.support": "Allal",
    "services.security": "Taɣellist",
    "services.marketing": "Abeɣɣu",
    "services.getStartedToday": "Bdu ass-a",
    "services.pricing.from": "Seg",
    "services.pricing.perHour": "/asrag",

    // Service categories
    "services.categories.webDevelopment": "Asnefli n web",
    "services.categories.webDevelopmentDesc": "Ismal web d isnasen web imaynuten yettwabnan s tetiknulujiyin tineggura",
    "services.categories.itSupport": "Allal IT",
    "services.categories.itSupportDesc": "Allal atiknikt n umuɣ d imeẓla n ufru n wuguren",
    "services.categories.wordpress": "Asnefli n WordPress",
    "services.categories.wordpressDesc": "Aẓaṛ WordPress imaynuten, plugins d usnefli n ismal web",
    "services.categories.seo": "Asnerni SEO",
    "services.categories.seoDesc": "Asnerni n umsedday n unadi i usnernu n ubani-inek deg Internet",
    "services.categories.systemSecurity": "Taɣellist n unagraw",
    "services.categories.systemSecurityDesc": "Asenqed ačči n teɣellist d tifrat n umḥadda",
    "services.categories.customTools": "Ifecka imaynuten",
    "services.categories.customToolsDesc": "Tifrat n usenfar imaynuten d ifecka n uwurman",

    // IMEI Checker
    "imei.title": "Amsendiq n IMEI baṭel",
    "imei.subtitle": "Senqed talɣut n IMEI n ubenk-inek deg wakud baṭel",
    "imei.description": "Senqed deg wakud talɣut n IMEI n ubenk-inek. Senqed ma yella tilifonit-inek tettuakir, tettuḥbes neɣ ɣur-es uguren uqbel asiɣ neɣ azenzay.",
    "imei.enterImei": "Sekcem uṭṭun n IMEI",
    "imei.placeholder": "amedya: 123456789012345",
    "imei.findImei": "Af IMEI-inek s ubeddel *#06# neɣ senqed Iɣewwaṛen",
    "imei.checkImei": "Senqed IMEI",
    "imei.checking": "Senqed...",
    "imei.reset": "Ales asbeddu",
    "imei.error": "Tuccḍa",
    "imei.errorEnterImei": "Ssekcem uṭṭun IMEI",
    "imei.errorInvalidImei": "IMEI issefk ad yili s sṭaṭ 15 n yiḍeffen",
    "imei.errorInvalidImeiDesc": "IMEI arameɣtu",
    "imei.results": "Igmaḍ n usenqed n IMEI",
    "imei.whatIsImei": "D acu-t IMEI?",
    "imei.imeiDescription": "IMEI (International Mobile Equipment Identity) d uṭṭun asbalu n 15 n yiḍeffen i d-isemmal abenk-inek aziraz. Icudd i usenqed ma yella abenk yettuakir, yettuḥbes neɣ ɣur-es uguren uqbel asiɣ.",
    "imei.features.secure": "Iɣelsed d uslig",
    "imei.features.secureDesc": "Isefka-inek IMEI ttuselkamen s tɣellist ur ttuḥaznen ara deg iqeddacen-nneɣ",
    "imei.features.instant": "Igmaḍ deg wakud",
    "imei.features.instantDesc": "Awi talɣut tičči n IMEI deg kra n tasinin",
    "imei.features.free": "100% baṭel",
    "imei.features.freeDesc": "Ur yessefk ara usiwel, baṭel akk i useqdec",

    // Service Request Form
    "form.requestService": "Suter ameẓlu",
    "form.yourName": "Isem-inek",
    "form.emailAddress": "Tansa n imayl",
    "form.phoneNumber": "Uṭṭun n tilifonit",
    "form.yourBudget": "Abudget-inek",
    "form.selectBudget": "Fren amur n ubudget",
    "form.lessThan300": "Daw n $300",
    "form.budget300to500": "$300 - $500",
    "form.budget500to1000": "$500 - $1000",
    "form.budget1000to2000": "$1000 - $2000",
    "form.moreThan2000": "Ugar n $2000",
    "form.contactForPricing": "Nermes i usawal n yizen",
    "form.serviceInterested": "Ameẓlu i deg tebɣiḍ",
    "form.selectService": "Fren ameẓlu",
    "form.webDevelopment": "Asnefli n web",
    "form.itSupport": "Allal IT",
    "form.wordpressDevelopment": "Asnefli n WordPress",
    "form.seoOptimization": "Asnerni SEO",
    "form.systemSecurity": "Taɣellist n unagraw",
    "form.customToolsDevelopment": "Asnefli n ifecka imaynuten",
    "form.imeiFrpRemote": "IMEI, FRP d Anmeggag",
    "form.serverCardsGames": "Aqeddac, Tikarḍiwin d Uraren",
    "form.expertSupport": "Allal n umussnaw",
    "form.other": "Wayeḍ (ma ulac aɣilif efk-d asegzi deg yizen)",
    "form.projectDetails": "Telqayt n usenfar",
    "form.projectDetailsPlaceholder": "Ma ulac aɣilif glem-d asenfar-inek neɣ isra n umeẓlu s telqayt.",
    "form.submitRequest": "Azen asuter n umeẓlu",
    "form.submitting": "Ittazen...",
    "form.submitted": "Asuter n umeẓlu yettwazen!",
    "form.submittedDesc": "Tanemmirt ɣef wayen i d-tmuddim. Ad rreɣ-ak-d deg 24 n usragen.",
    "form.required": "*",

    // Jobs Page
    "jobs.title": "Af axeddim-inek i d-iteddun",
    "jobs.subtitle": "Af tiseɣfin deg ussuq n uxeddim i d-yettimɣuren deg Tunes",
    "jobs.available": "Ixeddamen yellan",
    "jobs.filters": "Isizdegen",
    "jobs.clear": "Sfeḍ",
    "jobs.searchJobs": "Nadi ixeddamen",
    "jobs.searchPlaceholder": "Azwel n uxeddim, awalen igenwan...",
    "jobs.location": "Adig",
    "jobs.locationPlaceholder": "Tamdint, tamnaḍt...",
    "jobs.category": "Taggayt",
    "jobs.selectCategory": "Fren taggayt",
    "jobs.jobType": "Anaw n uxeddim",
    "jobs.selectJobType": "Fren anaw n uxeddim",
    "jobs.fullTime": "Akud meṛṛa",
    "jobs.partTime": "Akud azgen",
    "jobs.contract": "Amgrad",
    "jobs.freelance": "Axeddim ilellay",
    "jobs.salaryRange": "Amur n uxlas (TND)",
    "jobs.urgencyLevel": "Aswir n tuhya",
    "jobs.urgency.low": "Meẓẓi",
    "jobs.urgency.medium": "Alemmas",
    "jobs.urgency.high": "Meqqer",
    "jobs.activeFilters": "Isizdegen urmiden",
    "jobs.listView": "Tamuɣli n tebdart",
    "jobs.mapView": "Tamuɣli n tkarḍa",
    "jobs.loading": "Asali n ixeddamen...",
    "jobs.noJobs": "Ulac ixeddamen i yesnemlayen d isebdaden-inek.",
    "jobs.error": "Tuccḍa deg usali n ixeddamen. Ɛreḍ tikelt-nniḍen ticki.",

    // Common
    "common.loading": "Asali...",
    "common.error": "Tuccḍa",
    "common.success": "Yedda",
    "common.cancel": "Sefsex",
    "common.save": "Sekles",
    "common.edit": "Ẓreg",
    "common.delete": "Kkes",
    "common.confirm": "Sentem",
    "common.close": "Mdel",
    "common.search": "Nadi",
    "common.filter": "Sizdeg",
    "common.sort": "Smizzwer",
    "common.view": "Ẓer",
    "common.apply": "Snes",
    "common.reset": "Ales asbeddu",
    "common.back": "Uɣal",
    "common.next": "I d-iteddun",
    "common.previous": "Amezwaru",
    "common.submit": "Azen",
    "common.name": "Isem",
    "common.email": "Imayl",
    "common.phone": "Tilifonit",
    "common.message": "Izen",
    "common.description": "Aglam",
    "common.title": "Azwel",
    "common.date": "Azemz",
    "common.time": "Akud",
    "common.status": "Addad",
    "common.action": "Tigawt",
    "common.actions": "Tigawin"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(getInitialLanguage);

  const setLanguage = (newLanguage: Language) => {
    setLanguageState(newLanguage);
    localStorage.setItem('language', newLanguage);
    
    // Update document direction for RTL languages
    if (newLanguage === 'ar') {
      document.documentElement.dir = 'rtl';
    } else {
      document.documentElement.dir = 'ltr';
    }
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  useEffect(() => {
    // Set initial direction based on language
    if (language === 'ar') {
      document.documentElement.dir = 'rtl';
    } else {
      document.documentElement.dir = 'ltr';
    }
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
